/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ksdfg
 */
import java.io.FileNotFoundException;
import org.json.simple.JSONObject; 
import java.io.PrintWriter;
import org.json.simple.parser.*;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class mainFrame extends javax.swing.JFrame {
    
    //JSONObject that everybody is going to use - might as well declare it just once.
    JSONObject meow;
    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        try {
            meow = (JSONObject) new JSONParser().parse(new FileReader("meow.json"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        meow.put("attendance", 0);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsT = new javax.swing.JLabel();
        dsPr = new javax.swing.JLabel();
        dsThAtt = new javax.swing.JButton();
        dsThMiss = new javax.swing.JButton();
        dsPrAtt = new javax.swing.JButton();
        dsPrMiss = new javax.swing.JButton();
        sepmThAtt = new javax.swing.JButton();
        sepmTh = new javax.swing.JLabel();
        sepmThMiss = new javax.swing.JButton();
        sepmPrAtt = new javax.swing.JButton();
        sepmPr = new javax.swing.JLabel();
        sepmPrMiss = new javax.swing.JButton();
        osThAtt = new javax.swing.JButton();
        osTh = new javax.swing.JLabel();
        osThMiss = new javax.swing.JButton();
        osPrAtt = new javax.swing.JButton();
        osPr = new javax.swing.JLabel();
        osPrMiss = new javax.swing.JButton();
        mmcThAtt = new javax.swing.JButton();
        mmcTh = new javax.swing.JLabel();
        mmcThMiss = new javax.swing.JButton();
        mmcPrAtt = new javax.swing.JButton();
        mmcPr = new javax.swing.JLabel();
        mmcPrMiss = new javax.swing.JButton();
        attendaceDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dsT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dsT.setText("DS Theory");

        dsPr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dsPr.setText("DS Pracs");

        dsThAtt.setText("+");

        dsThMiss.setText("-");

        dsPrAtt.setText("+");

        dsPrMiss.setText("-");

        sepmThAtt.setText("+");

        sepmTh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sepmTh.setText("SEPM Theory");

        sepmThMiss.setText("-");
        sepmThMiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepmThMissActionPerformed(evt);
            }
        });

        sepmPrAtt.setText("+");

        sepmPr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sepmPr.setText("SEPM Pracs");

        sepmPrMiss.setText("-");

        osThAtt.setText("+");

        osTh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        osTh.setText("OS Theory");

        osThMiss.setText("-");

        osPrAtt.setText("+");

        osPr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        osPr.setText("OS Pracs");

        osPrMiss.setText("-");

        mmcThAtt.setText("+");

        mmcTh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmcTh.setText("MMC Theory");

        mmcThMiss.setText("-");

        mmcPrAtt.setText("+");

        mmcPr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmcPr.setText("MMC Pracs");

        mmcPrMiss.setText("-");

        attendaceDisplay.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        attendaceDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Attendance"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attendaceDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmcThAtt)
                                .addGap(18, 18, 18)
                                .addComponent(mmcTh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(osPrAtt)
                                .addGap(18, 18, 18)
                                .addComponent(osPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(osThAtt)
                                .addGap(18, 18, 18)
                                .addComponent(osTh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sepmPrAtt)
                                .addGap(18, 18, 18)
                                .addComponent(sepmPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sepmThAtt)
                                .addGap(18, 18, 18)
                                .addComponent(sepmTh))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dsThAtt)
                                    .addComponent(dsPrAtt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dsT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dsPr, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mmcPrAtt)
                                .addGap(18, 18, 18)
                                .addComponent(mmcPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dsThMiss)
                            .addComponent(dsPrMiss)
                            .addComponent(sepmThMiss)
                            .addComponent(sepmPrMiss)
                            .addComponent(osThMiss)
                            .addComponent(osPrMiss)
                            .addComponent(mmcThMiss)
                            .addComponent(mmcPrMiss))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dsT)
                    .addComponent(dsThAtt)
                    .addComponent(dsThMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dsPr)
                    .addComponent(dsPrAtt)
                    .addComponent(dsPrMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sepmTh)
                    .addComponent(sepmThAtt)
                    .addComponent(sepmThMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sepmPr)
                    .addComponent(sepmPrAtt)
                    .addComponent(sepmPrMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osTh)
                    .addComponent(osThAtt)
                    .addComponent(osThMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osPr)
                    .addComponent(osPrAtt)
                    .addComponent(osPrMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmcTh)
                    .addComponent(mmcThAtt)
                    .addComponent(mmcThMiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmcPr)
                    .addComponent(mmcPrAtt)
                    .addComponent(mmcPrMiss))
                .addGap(18, 18, 18)
                .addComponent(attendaceDisplay)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sepmThMissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sepmThMissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sepmThMissActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendaceDisplay;
    private javax.swing.JLabel dsPr;
    private javax.swing.JButton dsPrAtt;
    private javax.swing.JButton dsPrMiss;
    private javax.swing.JLabel dsT;
    private javax.swing.JButton dsThAtt;
    private javax.swing.JButton dsThMiss;
    private javax.swing.JLabel mmcPr;
    private javax.swing.JButton mmcPrAtt;
    private javax.swing.JButton mmcPrMiss;
    private javax.swing.JLabel mmcTh;
    private javax.swing.JButton mmcThAtt;
    private javax.swing.JButton mmcThMiss;
    private javax.swing.JLabel osPr;
    private javax.swing.JButton osPrAtt;
    private javax.swing.JButton osPrMiss;
    private javax.swing.JLabel osTh;
    private javax.swing.JButton osThAtt;
    private javax.swing.JButton osThMiss;
    private javax.swing.JLabel sepmPr;
    private javax.swing.JButton sepmPrAtt;
    private javax.swing.JButton sepmPrMiss;
    private javax.swing.JLabel sepmTh;
    private javax.swing.JButton sepmThAtt;
    private javax.swing.JButton sepmThMiss;
    // End of variables declaration//GEN-END:variables
}
